import {
  Home,
  Profile,
  Store,
  Contacts,
  Login,
  Logout,
  Admin,
  CartPage,
  ProductsManagement,
  UsersManagement,
  BlogsManagement,
  PaymentsManagement,
  AllergensManagement,
  IngredientsManagement,
  VouchersManagement,
  CategoryManagement,
  LocationsManagement,
  ChangePassword,
  ForgottenPassword,
  NotFound
} from "src/pages";
import BlogPage from "../pages/BlogPage/BlogPage";
import BlogPost from '../pages/BlogPost/BlogPost';
import ProductPage from '../pages/ProductPage/ProductPage'

export const nav = [
  {
    path: "/",
    name: "Home",
    element: <Home />,
    isMenu: true,
    isPrivate: false,
  },
  {
    path: "/store",
    name: "Store",
    element: <Store />,
    isMenu: true,
    isPrivate: false,
  },
  {
    path: "/contacts",
    name: "Contacts",
    element: <Contacts />,
    isMenu: true,
    isPrivate: false,
  },
  {
    path: "/login",
    name: "Login",
    element: <Login />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/register",
    name: "Register",
    element: <Login />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/forgotten-password",
    name: "ForgottenPassword",
    element: <ForgottenPassword />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/password-reset",
    name: "PasswordReset",
    element: <ForgottenPassword />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/change-password/:token",
    name: "ChangePassword",
    element: <ChangePassword />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/logout",
    name: "Logout",
    element: <Logout />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/profile",
    name: "Profile",
    element: <Profile />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/blog",
    name: "Blog",
    element: <BlogPage />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/blog/:id",
    name: "BlogPost",
    element: <BlogPost />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/store/:id",
    name: "ProductPage",
    element: <ProductPage />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/cart",
    name: "CartPage",
    element: <CartPage />,
    isMenu: false,
    isPrivate: false,
  },
  {
    path: "/admin",
    name: "Admin",
    element: <Admin />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/products",
    name: "ProductsManagement",
    element: <ProductsManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/users",
    name: "UsersManagement",
    element: <UsersManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/allergens",
    name: "AllergensManagement",
    element: <AllergensManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/blogs",
    name: "BlogsManagement",
    element: <BlogsManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/payments",
    name: "PaymentsManagement",
    element: <PaymentsManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/vouchers",
    name: "VouchersManagement",
    element: <VouchersManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/ingredients",
    name: "IngredientsManagement",
    element: <IngredientsManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/categories",
    name: "CategoryManagement",
    element: <CategoryManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "/admin/locations",
    name: "LocationsManagment",
    element: <LocationsManagement />,
    isMenu: false,
    isPrivate: false,
    isAdminPanelOnly: true,
  },
  {
    path: "*",
    name: "Not Found",
    element: <NotFound />,
    isMenu: true,
    isPrivate: false,
  }
];
